#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";

const params = {};
const args = process.argv
	.splice(2, Infinity)
	.map((item) => {
		if (item[0] == "-") {
			// it's a parameter
			const name = item.substring(1, Infinity).split("=")[0];
			const value = item.substring(item.indexOf("=") + 1, Infinity);

			params[name] = value;

			return undefined;
		}

		return item;
	})
	.filter((item) => item !== undefined);

if (args.length == 0) {
	console.log("\x1b[31mYou need to provide a directory to package!\x1b[0m");
	process.exit();
}

const input = path.resolve(process.cwd(), args[0]);
const output = path.resolve(process.cwd(), args[1] || "./app.idx");

async function checkOutput() {
	let content;
	try {
		content = await fs.readFile(output, { encoding: "utf8" });
	} catch (e) {}

	if (content !== undefined) {
		console.error("\x1b[31mOutput directory isn't empty!\x1b[0m");
		process.exit();
	}
}

if (Boolean(params.override) !== true) {
	// insure we don't override a pre-existing file
	await checkOutput();
}

// package info
const pkg = {
	files: {},
	directories: []
};

async function incrementor(result) {
	if (params.incrementor !== undefined) {
		const incrementDir = path.resolve(
			process.cwd(),
			args[0],
			"packages.json"
		);

		let content;

		try {
			content = JSON.parse((await fs.readFile(incrementDir)).toString());

			// check if the indexes are the same
			try {
				const oldIndex = (await fs.readFile(output)).toString();

				// if they are the same, don't increment
				if (oldIndex == result) {
					return;
				}
			} catch {}

		} catch {
			content = { packages: 0 };
		}

		content.packages++;

		await fs.writeFile(incrementDir, JSON.stringify(content, null, 4));
	}
}

// walk the folder
async function walk(directory, isRoot = false) {
	const ls = await fs.readdir(directory);

	for (const item of ls) {
		if (item == "package.json") {
			if (isRoot) {
				continue;
			}
		}
		const dir = path.resolve(directory, item);

		const stat = await fs.stat(dir);
		const isDir = stat.isDirectory();

		const relative = path.relative(input, dir);

		if (isDir) {
			// folder
			pkg.directories.push(relative);
			await walk(dir, false);
		} else {
			// file
			pkg.files[relative] = await fs.readFile(dir, { encoding: "utf8" });
		}
	}
}

await walk(input, true);

// stringify it
const result = JSON.stringify(pkg, null, 8);

incrementor(result);

await fs.writeFile(output, result);
console.log("App packaged to '\x1b[32m" + output + "\x1b[0m' successfully!");
