#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";

// mime
import { Mime } from "mime/lite";
import standardTypes from "mime/types/standard.js";
import otherTypes from "mime/types/other.js";
const mime = new Mime(standardTypes, otherTypes);

// custom types
mime.define(
	{
		"text/x-typescript": ["ts", "tsx"]
	},
	true
);
mime.define(
	{
		"text/x-constellation-runner-language": ["crl"]
	},
	true
);

const params = {};
const args = process.argv
	.splice(2, Infinity)
	.map((item) => {
		if (item[0] == "-") {
			// it's a parameter
			const name = item.substring(1, Infinity).split("=")[0];
			const value = item.substring(item.indexOf("=") + 1, Infinity);

			params[name] = value;

			return undefined;
		}

		return item;
	})
	.filter((item) => item !== undefined);

if (args.length == 0) {
	console.log("\x1b[31mYou need to provide a directory to package!\x1b[0m");
	process.exit();
}

const input = path.resolve(process.cwd(), args[0]);
const output = path.resolve(process.cwd(), args[1] || "./app.idx");

async function checkOutput() {
	let content;
	try {
		content = await fs.readFile(output, { encoding: "utf8" });
	} catch (e) {}

	if (content !== undefined) {
		console.error(
			`\x1b[31mOutput directory isn't empty! (Packaging ${output})\x1b[0m`
		);
		process.exit();
	}
}

if (Boolean(params.override) !== true) {
	// insure we don't override a pre-existing file
	await checkOutput();
}

async function tcpkg(fs, packageDirectory) {
	// package info
	const pkg = {
		files: {},
		directories: [],
		version: 2
	};

	// walk the folder
	async function walk(directory) {
		const contents = await fs.readdir(directory);

		for (const item of contents) {
			if (item.endsWith(".map")) continue;

			// determine the absolute path of the file
			const dir = fs.resolve(directory, item);

			// determine if the path is a directory or not
			const stat = await fs.stat(dir);
			if (stat == undefined)
				throw new Error(
					"Stat is undefined for a file that *should* exist?"
				);

			const isDir = stat.isDirectory();

			// get the *relative* path
			const relative = fs.relative(packageDirectory, dir);

			if (isDir) {
				// folders can simply be added to the directories list
				pkg.directories.push(relative);
				await walk(dir);
			} else {
				// files require MIME-type to determine if they are binary or not, because binary images are managed as DATA-URIs.

				try {
					const type = mime.getType(dir) ?? "text/plain";
					const isText =
						type.startsWith("text/") ||
						type.includes("xml") ||
						type.includes("javascript") ||
						type.includes("typescript") ||
						type.includes("json");

					const content = isText
						? await fs.readFile(dir, {
								encoding: "utf8"
							})
						: `data:${type};base64,${(await fs.readFile(dir)).toString("base64")}`;
					const stats = await fs.stat(dir);

					if (!content || !stats)
						throw new Error(
							`"Unexpected undefined when reading/statting file at ${dir}`
						);

					pkg.files[relative] = {
						contents: content,

						created: stats.ctime,
						modified: stats.mtime,

						size: stats.size
					};
				} catch (e) {
					throw new Error(
						`Error ${e} occurred when packaging ${dir}. it has not been included in the index.`
					);
				}
			}
		}
	}

	try {
		await walk(packageDirectory);
	} catch (e) {
		throw e;
	}

	return pkg;
}

const pkg = await tcpkg({ ...fs, ...path }, input);

// stringify it
const result = JSON.stringify(pkg, null, 8);

await fs.writeFile(output, result);
console.log("App packaged to '\x1b[32m" + output + "\x1b[0m' successfully!");
